exp 6 vector addition


In [1]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(a.dot(b))
print(2*a)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
32
[2 4 6]


exp 1 Data Preprocessing

In [2]:
import pandas as pd
data = pd.DataFrame({
    'Country': ['France', 'Spain', 'Germany', 'Spain', 'Germany', 'France', 'Spain', 'France', 'Germany', 'France'],
    'Age': [44.0, 27.0, 30.0, 38.0, 40.0, 35.0, np.nan, 48.0, 50.0, 37.0],
    'Salary': [72000.0, 48000.0, 54000.0, 61000.0, np.nan, 58000.0, 52000.0, 79000.0, 83000.0, 67000.0],
    'Purchased': ['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
})
data.to_csv("data.csv",index=False)

In [3]:
data = pd.read_csv("data.csv")

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [5]:
data.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [6]:
newdata = data.dropna()

In [7]:
newdata.isnull().sum()

Country      0
Age          0
Salary       0
Purchased    0
dtype: int64

In [8]:
age_mean = data['Age'].mean()
data['Age'].fillna(value = age_mean, inplace=True)

In [9]:
salary_mean = data['Salary'].mean()
data['Salary'].fillna(value = salary_mean, inplace=True)
data.isnull().sum()

Country      0
Age          0
Salary       0
Purchased    0
dtype: int64

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
cat_cols = ['Country','Purchased']
for i in cat_cols:
  data[i] = le.fit_transform(data[i])
data.head()

Country   Age        Salary  Purchased
0        0  44.0  72000.000000          0
1        2  27.0  48000.000000          1
2        1  30.0  54000.000000          0
3        2  38.0  61000.000000          0
4        1  40.0  63777.777778          1

In [11]:
from sklearn.preprocessing import MinMaxScaler
mmscaler = MinMaxScaler(feature_range=(0,1))
newdata = mmscaler.fit_transform(data)
newdata = pd.DataFrame(newdata, columns = data.columns)
newdata

Country       Age    Salary  Purchased
0      0.0  0.739130  0.685714        0.0
1      1.0  0.000000  0.000000        1.0
2      0.5  0.130435  0.171429        0.0
3      1.0  0.478261  0.371429        0.0
4      0.5  0.565217  0.450794        1.0
5      0.0  0.347826  0.285714        1.0
6      1.0  0.512077  0.114286        0.0
7      0.0  0.913043  0.885714        1.0
8      0.5  1.000000  1.000000        0.0
9      0.0  0.434783  0.542857        1.0

In [12]:
from sklearn.feature_selection import SelectKBest,chi2
bestfit = SelectKBest(score_func= chi2,k=3)
x = ['Country','Age','Salary']
y = ['Purchased']
fit = bestfit.fit(newdata[x],newdata[y])
pd.DataFrame({"Columns" : x, "Scores":fit.scores_})

Columns    Scores
0  Country  0.500000
1      Age  0.070076
2   Salary  0.007011